# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gossiping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewKeywords',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_keyword', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'new_keywords',
                'managed': False,
            },
        ),
    ]
