# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gossiping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bisexual',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bisexualcontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bisexualreply',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='femininesex',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='femininesexcontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='femininesexreply',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gay',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gaycontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gayreply',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gossiping',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gossipingcontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gossipingreply',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='keywords',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='newkeywords',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sexcontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sexreply',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usersavepost',
            options={'managed': False},
        ),
    ]
