# Generated by Django 2.0 on 2017-12-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gossiping', '0003_auto_20170929_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavePostAnalysisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=32)),
                ('user_id', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=100)),
                ('dataType', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User_Save_Post_analysis_data',
                'managed': False,
            },
        ),
    ]
