# Generated by Django 2.0.3 on 2018-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gossiping', '0003_auto_20170929_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickle', models.TextField(blank=True, null=True)),
                ('dataType', models.CharField(blank=True, max_length=45, null=True)),
                ('class_id', models.CharField(blank=True, max_length=45, null=True)),
                ('user_id', models.CharField(blank=True, max_length=45, null=True)),
                ('other', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user_analysis_result',
            },
        ),
    ]
